import { and, desc, eq, gte, inArray, isNotNull, lt, sql } from 'drizzle-orm';
import { ALARM_TYPES } from '@platform/shared/contracts';
import {
  zonedDateParts,
  zonedDayKey,
  zonedMinutesOfDay,
  zonedTimeToEpoch,
} from '@platform/shared/clock';
import {
  SweepSummarySchema,
  type MorningReportData,
  type Report,
  type ReportsResponse,
  type SweepSummary,
} from '@platform/shared/dto';
import type { Db } from '../../db/index.js';
import {
  assets,
  automationRuns,
  bookings,
  locations,
  notifications,
  reports,
  users,
  type ReportRow,
  type TenantRow,
} from '../../db/schema/index.js';
import { withTenant } from '../../db/tenant.js';
import { notFound } from '../../lib/errors.js';
import { renderMorningReportEmail } from '../../templates/email/morning-report.js';
import type { AuditService } from '../audit/audit.service.js';
import type { ClockService } from '../clock/clock.service.js';
import type { LiveStateService } from '../live/live-state.service.js';
import type { Mailer } from './mail.service.js';
import type { SavingsService } from './savings.service.js';

/** The report is generated once the business clock passes this hour. */
export const MORNING_REPORT_HOUR = 7;
/** The evening a report covers: the business day 12 hours before now (07:00 → yesterday). */
const LOOKBACK_MS = 12 * 3_600_000;
/** Overnight window (platform zone) whose alarms and releases the report counts. */
const EVENING_HOUR = 18;
const SWEEP_KEYS = ['evening_sweep', 'holiday_mode'];
const ALARM_KINDS = ['alarm', 'night.anomaly', 'asset.unreachable'];

export function toReportDto(row: ReportRow): Report {
  return {
    id: row.id,
    kind: row.kind as Report['kind'],
    period: row.period,
    generatedAt: row.generatedAt.toISOString(),
    pdfPath: row.pdfPath,
    data: row.data,
  };
}

/** Business date the morning report covers when generated at `now`. Pure. */
export function reportDateFor(now: number, timeZone: string): string {
  return zonedDayKey(now - LOOKBACK_MS, timeZone);
}

/** Reads a sweep run's summary into the report shape; null when the run did not sweep. Pure. */
export function sweepSummaryFrom(summary: Record<string, unknown>): SweepSummary | null {
  const parsed = SweepSummarySchema.safeParse({
    businessTime: summary.businessTime,
    roomsOff: summary.roomsOff ?? [],
    roomsSkipped: summary.roomsSkipped ?? [],
    commandsSent: summary.commandsSent ?? 0,
    zonesKept: summary.zonesKept ?? [],
    estimatedKwhSaved: summary.estimatedKwhSaved ?? 0,
    estimatedCostSaved: summary.estimatedCostSaved ?? 0,
    measuredKwhSaved: summary.measuredKwhSaved ?? null,
    measuredCostSaved: summary.measuredCostSaved ?? null,
  });
  return parsed.success ? parsed.data : null;
}

/**
 * The morning report: what last evening's sweep switched off and kept on, what it saved
 * (estimated until measured baselines exist), and what happened overnight. Generated by the
 * automation tick once the business clock passes 07:00, or on demand; emailed to operations.
 */
export class MorningReportService {
  constructor(
    private readonly db: Db,
    private readonly audit: AuditService,
    private readonly clock: ClockService,
    private readonly live: LiveStateService,
    private readonly mailer: Mailer,
    private readonly timeZone: string,
    private readonly realNow: () => number = Date.now,
    private readonly savings: SavingsService | null = null,
  ) {}

  async list(
    tenantId: string,
    query: { kind?: string; page: number; pageSize: number },
  ): Promise<ReportsResponse> {
    return withTenant(this.db, tenantId, async (tx) => {
      const where = query.kind ? eq(reports.kind, query.kind) : undefined;
      const items = await tx
        .select()
        .from(reports)
        .where(where)
        .orderBy(desc(reports.period), desc(reports.generatedAt))
        .limit(query.pageSize)
        .offset(query.page * query.pageSize);
      const all = await tx.select({ id: reports.id }).from(reports).where(where);
      return {
        items: items.map(toReportDto),
        total: all.length,
        page: query.page,
        pageSize: query.pageSize,
      };
    });
  }

  async byId(tenantId: string, id: string): Promise<Report> {
    const [row] = await withTenant(this.db, tenantId, (tx) =>
      tx.select().from(reports).where(eq(reports.id, id)).limit(1),
    );
    if (!row) throw notFound('Report not found');
    return toReportDto(row);
  }

  /** Generates the report when 07:00 has passed and today's has not been written yet. */
  async dueCheck(tenant: TenantRow, now: number): Promise<Report | null> {
    if (zonedMinutesOfDay(now, this.timeZone) < MORNING_REPORT_HOUR * 60) return null;
    const date = reportDateFor(now, this.timeZone);
    const existing = await withTenant(this.db, tenant.id, (tx) =>
      tx
        .select({ id: reports.id })
        .from(reports)
        .where(and(eq(reports.kind, 'morning'), eq(reports.period, date)))
        .limit(1),
    );
    if (existing.length) return null;
    return this.generate(tenant, { date, trigger: 'schedule' });
  }

  /** Builds, stores and emails the report for a business date (default: last evening). */
  async generate(
    tenant: TenantRow,
    opts: { date?: string; trigger: string; send?: boolean } = { trigger: 'manual' },
  ): Promise<Report> {
    const now = await this.clock.now(tenant.key);
    const date = opts.date ?? reportDateFor(now, this.timeZone);
    const data = await this.collect(tenant, date);
    const recipients = opts.send === false ? [] : await this.recipients(tenant.id);
    if (recipients.length) {
      const mail = renderMorningReportEmail(tenant.brand, data);
      try {
        await this.mailer.send({ to: recipients, ...mail });
        data.emailedTo = recipients;
      } catch {
        data.emailedTo = [];
      }
    }
    const row = await withTenant(this.db, tenant.id, async (tx) => {
      await tx.delete(reports).where(and(eq(reports.kind, 'morning'), eq(reports.period, date)));
      const [inserted] = await tx
        .insert(reports)
        .values({
          tenantId: tenant.id,
          kind: 'morning',
          period: date,
          generatedAt: new Date(this.realNow()),
          data: { ...data, trigger: opts.trigger },
        })
        .returning();
      await this.audit.record(tx, {
        tenantId: tenant.id,
        action: 'report.generate',
        entityType: 'report',
        entityId: inserted!.id,
        after: { kind: 'morning', period: date, trigger: opts.trigger, emailedTo: data.emailedTo },
      });
      return inserted!;
    });
    return toReportDto(row);
  }

  private async recipients(tenantId: string): Promise<string[]> {
    return withTenant(this.db, tenantId, async (tx) => {
      const ops = await tx
        .select({ email: users.email })
        .from(users)
        .where(eq(users.role, 'OPS_MANAGER'));
      if (ops.length) return ops.map((u) => u.email);
      const admins = await tx
        .select({ email: users.email })
        .from(users)
        .where(eq(users.role, 'TENANT_ADMIN'));
      return admins.map((u) => u.email);
    });
  }

  /** Gathers the report data for one business date. */
  async collect(tenant: TenantRow, date: string): Promise<MorningReportData> {
    const [y, m, d] = date.split('-').map(Number);
    const dayParts = {
      ...zonedDateParts(this.realNow(), this.timeZone),
      year: y!,
      month: m!,
      day: d!,
    };
    const dayStart = zonedTimeToEpoch(
      { ...dayParts, hour: 0, minute: 0, second: 0 },
      this.timeZone,
    );
    const evening = zonedTimeToEpoch(
      { ...dayParts, hour: EVENING_HOUR, minute: 0, second: 0 },
      this.timeZone,
    );
    const nextMorning =
      zonedTimeToEpoch(
        { ...dayParts, hour: MORNING_REPORT_HOUR, minute: 0, second: 0 },
        this.timeZone,
      ) +
      24 * 3_600_000;

    const { sweepRows, released, misplaced, alarmRows } = await withTenant(
      this.db,
      tenant.id,
      async (tx) => ({
        sweepRows: await tx
          .select()
          .from(automationRuns)
          .where(
            and(
              inArray(automationRuns.key, SWEEP_KEYS),
              sql`${automationRuns.summary} ->> 'actedDay' = ${date}`,
            ),
          )
          .orderBy(desc(automationRuns.startedAt))
          .limit(5),
        released: await tx
          .select({ id: bookings.id })
          .from(bookings)
          .where(
            and(
              eq(bookings.status, 'RELEASED'),
              gte(bookings.start, new Date(dayStart)),
              lt(bookings.start, new Date(dayStart + 24 * 3_600_000)),
            ),
          ),
        misplaced: await tx
          .select({ code: assets.code, room: locations.code })
          .from(assets)
          .innerJoin(locations, eq(locations.id, assets.misplacedRoomId))
          .where(isNotNull(assets.misplacedRoomId)),
        alarmRows: await tx
          .select({ subject: notifications.subject, kind: notifications.kind })
          .from(notifications)
          .where(
            and(
              inArray(notifications.kind, ALARM_KINDS),
              gte(notifications.createdAt, new Date(evening)),
              lt(notifications.createdAt, new Date(nextMorning)),
            ),
          ),
      }),
    );
    const sweepRun = sweepRows.find(
      (r) => r.summary.sweepDay === date && r.summary.actedDay === date,
    );
    const sweep = sweepRun ? sweepSummaryFrom(sweepRun.summary) : null;
    if (sweep && this.savings) {
      const measured = await this.savings
        .measuredForNight(tenant, date, this.realNow())
        .catch(() => null);
      if (measured !== null) {
        sweep.measuredKwhSaved = measured;
        sweep.measuredCostSaved = Math.round(measured * Number(tenant.tariffPerKwh) * 100) / 100;
      }
    }
    const alarms = new Set(alarmRows.map((a) => `${a.kind}:${a.subject ?? ''}`));
    const snapshot = await this.live.snapshot(tenant.key);
    const unreachable = snapshot
      .filter(
        (d) => d.deviceType === 'laptop' && d.activeAlarms.includes(ALARM_TYPES.assetUnreachable),
      )
      .map((d) => d.deviceCode)
      .sort();
    return {
      date,
      currency: tenant.currency,
      sweep,
      alarmsOvernight: alarms.size,
      releasedBookings: released.length,
      misplacedAssets: misplaced,
      unreachableAssets: unreachable,
      emailedTo: [],
    };
  }
}
